### ISSUE TITLE
Questions about run time of the code

### ISSUE THREAD

**Issue by 1187828594** [Kaimaoge/SATCN#1]
Hello, could you give me a rough description of how long the code needs to run? Due to the shortage of laboratory resources, this is the first issue that I may need to care about. be deeply grateful.

**Comment by Kaimaoge** [comment]
Hi, most of the run-time is used for reading the dataset. I will try to fix this issue in the future. If you are running the code for METR-LA, it needs a lot of hard disc space to restore the training and test data.
